#pragma once

#define CMD_REPLY_BOOL_LEN 1
#define CMD_REPLY_VAR_LEN -1

//digital

#define CMD_PIN_MODE 0x01
#define CMD_PIN_MODE_RL CMD_REPLY_BOOL_LEN

#define CMD_DIGITAL_WRITE 0x02
#define CMD_DIGITAL_WRITE_RL CMD_REPLY_BOOL_LEN

#define CMD_DIGITAL_READ 0x03
#define CMD_DIGITAL_READ_RL (CMD_REPLY_BOOL_LEN + 1)

#define CMD_DIGITAL_ATTACH_INTERRUPT 0x04
#define CMD_DIGITAL_ATTACH_INTERRUPT_RL CMD_REPLY_BOOL_LEN

#define CMD_DIGITAL_DETACH_INTERRUPT 0x05
#define CMD_DIGITAL_DETACH_INTERRUPT_RL CMD_REPLY_BOOL_LEN

#define EVENT_DIGITAL_INTERRUPT 0x06

#define MAX_INTERRUPT_NUMBER 2

#define EVENT_MESSAGE_SIZE (1 + MAX_INTERRUPT_NUMBER)

//SPI

#define CMD_SPI_BEGIN 0x11
#define CMD_SPI_BEGIN_RL CMD_REPLY_BOOL_LEN

#define CMD_SPI_BEGIN_TRANSACTION 0x12
#define CMD_SPI_BEGIN_TRANSACTION_RL CMD_REPLY_BOOL_LEN

#define CMD_SPI_TRANSFER 0x13
#define CMD_SPI_TRANSFER_RL CMD_REPLY_VAR_LEN

#define CMD_SPI_END_TRANSACTION 0x14
#define CMD_SPI_END_TRANSACTION_RL CMD_REPLY_BOOL_LEN

#define CMD_SPI_END 0x15
#define CMD_SPI_END_RL CMD_REPLY_BOOL_LEN

#define CMD_SPI_READ 0x16
#define CMD_SPI_READ_RL CMD_REPLY_VAR_LEN

#define CMD_SPI_WRITE 0x17
#define CMD_SPI_WRITE_RL CMD_REPLY_BOOL_LEN

//Wire

#define CMD_WIRE_BEGIN 0x21
#define CMD_WIRE_BEGIN_RL (CMD_REPLY_BOOL_LEN)

#define CMD_WIRE_REQUEST_FROM 0x22
#define CMD_WIRE_REQUEST_FROM_RL CMD_REPLY_VAR_LEN

#define CMD_WIRE_TRANSMISSION 0x23
#define CMD_WIRE_TRANSMISSION_RL (CMD_REPLY_BOOL_LEN + 1)

//Serial

#define CMD_SERIAL_BEGIN 0x31
#define CMD_SERIAL_WRITE 0x32
#define CMD_SERIAL_AVAIL 0x33
#define CMD_SERIAL_READ 0x34
#define CMD_SERIAL_FLUSH 0x35
#define CMD_SERIAL_PEEK 0x36
#define CMD_SERIAL_END 0x37

//analog

#define CMD_ANALOG_READ 0x41
#define CMD_ANALOG_READ_RL (CMD_REPLY_BOOL_LEN + 2)

#define CMD_ANALOG_REFERENCE 0x42
#define CMD_ANALOG_REFERENCE_RLEN 0x01

#define CMD_ANALOG_WRITE 0x43
#define CMD_ANALOG_WRITE_RLEN 0x01

#define CMD_ANALOG_READ_RESOLUTION 0x44
#define CMD_ANALOG_WRITE_RESOLUTION 0x45

//system

#define CMD_SYS_SET_DEBUG 0xF1
#define CMD_SYS_SET_DEBUG_RL CMD_REPLY_BOOL_LEN